
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/felipetrost/.local/lib/python3.12/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.11.8-200.fc40.x86_64 - x86_64
...
